/*
 * generated by Xtext 2.18.0
 */
package org.xtext.example.mydsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.mydsl.ide.contentassist.antlr.internal.InternalMyDslParser;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MyDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MyDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
			builder.put(grammarAccess.getDomainAccess().getGroup(), "rule__Domain__Group__0");
			builder.put(grammarAccess.getEntityAccess().getGroup(), "rule__Entity__Group__0");
			builder.put(grammarAccess.getEntitiesAccess().getGroup(), "rule__Entities__Group__0");
			builder.put(grammarAccess.getPhotoAccess().getGroup(), "rule__Photo__Group__0");
			builder.put(grammarAccess.getAlbumAccess().getGroup(), "rule__Album__Group__0");
			builder.put(grammarAccess.getUserDomainAccess().getGroup(), "rule__UserDomain__Group__0");
			builder.put(grammarAccess.getFunctionalityAccess().getGroup(), "rule__Functionality__Group__0");
			builder.put(grammarAccess.getFunctionalitiesAccess().getGroup(), "rule__Functionalities__Group__0");
			builder.put(grammarAccess.getProfileManagementAccess().getGroup(), "rule__ProfileManagement__Group__0");
			builder.put(grammarAccess.getProfileManagementFunctionsAccess().getGroup(), "rule__ProfileManagementFunctions__Group__0");
			builder.put(grammarAccess.getAppAccessAccess().getGroup(), "rule__AppAccess__Group__0");
			builder.put(grammarAccess.getAppAccessFunctionsAccess().getGroup(), "rule__AppAccessFunctions__Group__0");
			builder.put(grammarAccess.getAlbumManagementAccess().getGroup(), "rule__AlbumManagement__Group__0");
			builder.put(grammarAccess.getAlbumManagementFunctionsAccess().getGroup(), "rule__AlbumManagementFunctions__Group__0");
			builder.put(grammarAccess.getPhotoActionsAccess().getGroup(), "rule__PhotoActions__Group__0");
			builder.put(grammarAccess.getPhotoActionsFunctionsAccess().getGroup(), "rule__PhotoActionsFunctions__Group__0");
			builder.put(grammarAccess.getLandingActionsAccess().getGroup(), "rule__LandingActions__Group__0");
			builder.put(grammarAccess.getLandingFunctionsAccess().getGroup(), "rule__LandingFunctions__Group__0");
			builder.put(grammarAccess.getDomainConnectionAccess().getGroup(), "rule__DomainConnection__Group__0");
			builder.put(grammarAccess.getDomainRelationsAccess().getGroup(), "rule__DomainRelations__Group__0");
			builder.put(grammarAccess.getArchitectureAccess().getGroup(), "rule__Architecture__Group__0");
			builder.put(grammarAccess.getTechnologyAccess().getGroup(), "rule__Technology__Group__0");
			builder.put(grammarAccess.getTechnologiesAccess().getGroup(), "rule__Technologies__Group__0");
			builder.put(grammarAccess.getReactAccess().getGroup(), "rule__React__Group__0");
			builder.put(grammarAccess.getReactModulesAccess().getGroup(), "rule__ReactModules__Group__0");
			builder.put(grammarAccess.getReactSubModulesAccess().getGroup(), "rule__ReactSubModules__Group__0");
			builder.put(grammarAccess.getReactConfigurationAccess().getGroup(), "rule__ReactConfiguration__Group__0");
			builder.put(grammarAccess.getReactDependenciesAccess().getGroup(), "rule__ReactDependencies__Group__0");
			builder.put(grammarAccess.getReactDependenciesRulesAccess().getGroup(), "rule__ReactDependenciesRules__Group__0");
			builder.put(grammarAccess.getSingleDependenciesAccess().getGroup(), "rule__SingleDependencies__Group__0");
			builder.put(grammarAccess.getPackageNameAccess().getGroup(), "rule__PackageName__Group__0");
			builder.put(grammarAccess.getPackageVersionAccess().getGroup(), "rule__PackageVersion__Group__0");
			builder.put(grammarAccess.getReactConfigurationsAccess().getGroup(), "rule__ReactConfigurations__Group__0");
			builder.put(grammarAccess.getReactComponentsAccess().getGroup(), "rule__ReactComponents__Group__0");
			builder.put(grammarAccess.getComponentsLogicAccess().getGroup(), "rule__ComponentsLogic__Group__0");
			builder.put(grammarAccess.getComponentsUIAccess().getGroup(), "rule__ComponentsUI__Group__0");
			builder.put(grammarAccess.getReactActionsAccess().getGroup(), "rule__ReactActions__Group__0");
			builder.put(grammarAccess.getReactLibrariesAccess().getGroup(), "rule__ReactLibraries__Group__0");
			builder.put(grammarAccess.getReactInfoAccess().getGroup(), "rule__ReactInfo__Group__0");
			builder.put(grammarAccess.getSpringAccess().getGroup(), "rule__Spring__Group__0");
			builder.put(grammarAccess.getPostgreSQLAccess().getGroup(), "rule__PostgreSQL__Group__0");
			builder.put(grammarAccess.getAmazonWebServicesAccess().getGroup(), "rule__AmazonWebServices__Group__0");
			builder.put(grammarAccess.getModelAccess().getElementsAssignment_3(), "rule__Model__ElementsAssignment_3");
			builder.put(grammarAccess.getModelAccess().getElementsAssignment_4(), "rule__Model__ElementsAssignment_4");
			builder.put(grammarAccess.getModelAccess().getElementsAssignment_5(), "rule__Model__ElementsAssignment_5");
			builder.put(grammarAccess.getDomainAccess().getNameAssignment_1(), "rule__Domain__NameAssignment_1");
			builder.put(grammarAccess.getDomainAccess().getElementsAssignment_4(), "rule__Domain__ElementsAssignment_4");
			builder.put(grammarAccess.getDomainAccess().getElementsAssignment_5(), "rule__Domain__ElementsAssignment_5");
			builder.put(grammarAccess.getDomainAccess().getElementsAssignment_6(), "rule__Domain__ElementsAssignment_6");
			builder.put(grammarAccess.getEntityAccess().getElementsAssignment_3(), "rule__Entity__ElementsAssignment_3");
			builder.put(grammarAccess.getEntitiesAccess().getElementsAssignment_0(), "rule__Entities__ElementsAssignment_0");
			builder.put(grammarAccess.getEntitiesAccess().getElementsAssignment_1(), "rule__Entities__ElementsAssignment_1");
			builder.put(grammarAccess.getEntitiesAccess().getElementsAssignment_2(), "rule__Entities__ElementsAssignment_2");
			builder.put(grammarAccess.getPhotoAccess().getNameAssignment_1(), "rule__Photo__NameAssignment_1");
			builder.put(grammarAccess.getAlbumAccess().getNameAssignment_1(), "rule__Album__NameAssignment_1");
			builder.put(grammarAccess.getUserDomainAccess().getNameAssignment_1(), "rule__UserDomain__NameAssignment_1");
			builder.put(grammarAccess.getFunctionalityAccess().getElementsAssignment_3(), "rule__Functionality__ElementsAssignment_3");
			builder.put(grammarAccess.getFunctionalitiesAccess().getFunctionsAssignment_0(), "rule__Functionalities__FunctionsAssignment_0");
			builder.put(grammarAccess.getFunctionalitiesAccess().getElementsAssignment_1(), "rule__Functionalities__ElementsAssignment_1");
			builder.put(grammarAccess.getFunctionalitiesAccess().getItemsAssignment_2(), "rule__Functionalities__ItemsAssignment_2");
			builder.put(grammarAccess.getFunctionalitiesAccess().getResourcesAssignment_3(), "rule__Functionalities__ResourcesAssignment_3");
			builder.put(grammarAccess.getFunctionalitiesAccess().getAditionalsAssignment_4(), "rule__Functionalities__AditionalsAssignment_4");
			builder.put(grammarAccess.getProfileManagementAccess().getItemsAssignment_2(), "rule__ProfileManagement__ItemsAssignment_2");
			builder.put(grammarAccess.getProfileManagementFunctionsAccess().getNameAssignment_1(), "rule__ProfileManagementFunctions__NameAssignment_1");
			builder.put(grammarAccess.getProfileManagementFunctionsAccess().getNameAssignment_3(), "rule__ProfileManagementFunctions__NameAssignment_3");
			builder.put(grammarAccess.getAppAccessAccess().getItemsAssignment_2(), "rule__AppAccess__ItemsAssignment_2");
			builder.put(grammarAccess.getAppAccessFunctionsAccess().getNameAssignment_1(), "rule__AppAccessFunctions__NameAssignment_1");
			builder.put(grammarAccess.getAppAccessFunctionsAccess().getNameAssignment_3(), "rule__AppAccessFunctions__NameAssignment_3");
			builder.put(grammarAccess.getAlbumManagementAccess().getItemsAssignment_2(), "rule__AlbumManagement__ItemsAssignment_2");
			builder.put(grammarAccess.getAlbumManagementFunctionsAccess().getNameAssignment_1(), "rule__AlbumManagementFunctions__NameAssignment_1");
			builder.put(grammarAccess.getAlbumManagementFunctionsAccess().getNameAssignment_3(), "rule__AlbumManagementFunctions__NameAssignment_3");
			builder.put(grammarAccess.getPhotoActionsAccess().getItemsAssignment_2(), "rule__PhotoActions__ItemsAssignment_2");
			builder.put(grammarAccess.getPhotoActionsFunctionsAccess().getNameAssignment_1(), "rule__PhotoActionsFunctions__NameAssignment_1");
			builder.put(grammarAccess.getPhotoActionsFunctionsAccess().getNameAssignment_3(), "rule__PhotoActionsFunctions__NameAssignment_3");
			builder.put(grammarAccess.getPhotoActionsFunctionsAccess().getNameAssignment_5(), "rule__PhotoActionsFunctions__NameAssignment_5");
			builder.put(grammarAccess.getLandingActionsAccess().getItemsAssignment_2(), "rule__LandingActions__ItemsAssignment_2");
			builder.put(grammarAccess.getLandingFunctionsAccess().getNameAssignment_1(), "rule__LandingFunctions__NameAssignment_1");
			builder.put(grammarAccess.getLandingFunctionsAccess().getNameAssignment_3(), "rule__LandingFunctions__NameAssignment_3");
			builder.put(grammarAccess.getDomainConnectionAccess().getElementsAssignment_3(), "rule__DomainConnection__ElementsAssignment_3");
			builder.put(grammarAccess.getDomainRelationsAccess().getElementsAssignment_0(), "rule__DomainRelations__ElementsAssignment_0");
			builder.put(grammarAccess.getDomainRelationsAccess().getNameAssignment_1(), "rule__DomainRelations__NameAssignment_1");
			builder.put(grammarAccess.getDomainRelationsAccess().getElementsAssignment_4(), "rule__DomainRelations__ElementsAssignment_4");
			builder.put(grammarAccess.getDomainRelationsAccess().getElementsAssignment_6(), "rule__DomainRelations__ElementsAssignment_6");
			builder.put(grammarAccess.getDomainRelationsAccess().getNameAssignment_7(), "rule__DomainRelations__NameAssignment_7");
			builder.put(grammarAccess.getDomainRelationsAccess().getElementsAssignment_10(), "rule__DomainRelations__ElementsAssignment_10");
			builder.put(grammarAccess.getDomainRelationsAccess().getElementsAssignment_12(), "rule__DomainRelations__ElementsAssignment_12");
			builder.put(grammarAccess.getDomainRelationsAccess().getNameAssignment_13(), "rule__DomainRelations__NameAssignment_13");
			builder.put(grammarAccess.getDomainRelationsAccess().getElementsAssignment_16(), "rule__DomainRelations__ElementsAssignment_16");
			builder.put(grammarAccess.getDomainRelationsAccess().getElementsAssignment_18(), "rule__DomainRelations__ElementsAssignment_18");
			builder.put(grammarAccess.getDomainRelationsAccess().getNameAssignment_19(), "rule__DomainRelations__NameAssignment_19");
			builder.put(grammarAccess.getDomainRelationsAccess().getElementsAssignment_22(), "rule__DomainRelations__ElementsAssignment_22");
			builder.put(grammarAccess.getArchitectureAccess().getNameAssignment_2(), "rule__Architecture__NameAssignment_2");
			builder.put(grammarAccess.getTechnologyAccess().getNameAssignment_1(), "rule__Technology__NameAssignment_1");
			builder.put(grammarAccess.getTechnologyAccess().getElementsAssignment_4(), "rule__Technology__ElementsAssignment_4");
			builder.put(grammarAccess.getTechnologiesAccess().getFactorsAssignment_0(), "rule__Technologies__FactorsAssignment_0");
			builder.put(grammarAccess.getTechnologiesAccess().getFactorsAssignment_1(), "rule__Technologies__FactorsAssignment_1");
			builder.put(grammarAccess.getTechnologiesAccess().getFactorsAssignment_2(), "rule__Technologies__FactorsAssignment_2");
			builder.put(grammarAccess.getTechnologiesAccess().getFactorsAssignment_3(), "rule__Technologies__FactorsAssignment_3");
			builder.put(grammarAccess.getReactAccess().getNameAssignment_1(), "rule__React__NameAssignment_1");
			builder.put(grammarAccess.getReactAccess().getReactsAssignment_4(), "rule__React__ReactsAssignment_4");
			builder.put(grammarAccess.getReactModulesAccess().getReactmodulesAssignment_3(), "rule__ReactModules__ReactmodulesAssignment_3");
			builder.put(grammarAccess.getReactSubModulesAccess().getReactmodulesAssignment_0(), "rule__ReactSubModules__ReactmodulesAssignment_0");
			builder.put(grammarAccess.getReactSubModulesAccess().getReactmodulesAssignment_1(), "rule__ReactSubModules__ReactmodulesAssignment_1");
			builder.put(grammarAccess.getReactSubModulesAccess().getReactmodulesAssignment_2(), "rule__ReactSubModules__ReactmodulesAssignment_2");
			builder.put(grammarAccess.getReactSubModulesAccess().getReactmodulesAssignment_3(), "rule__ReactSubModules__ReactmodulesAssignment_3");
			builder.put(grammarAccess.getReactSubModulesAccess().getReactmodulesAssignment_4(), "rule__ReactSubModules__ReactmodulesAssignment_4");
			builder.put(grammarAccess.getReactConfigurationAccess().getDependenciesAssignment_1(), "rule__ReactConfiguration__DependenciesAssignment_1");
			builder.put(grammarAccess.getReactConfigurationAccess().getConfigurationsAssignment_2(), "rule__ReactConfiguration__ConfigurationsAssignment_2");
			builder.put(grammarAccess.getReactDependenciesAccess().getDependenciesAssignment_1(), "rule__ReactDependencies__DependenciesAssignment_1");
			builder.put(grammarAccess.getReactDependenciesRulesAccess().getNameAssignment_1(), "rule__ReactDependenciesRules__NameAssignment_1");
			builder.put(grammarAccess.getReactDependenciesRulesAccess().getDependenciesAssignment_2(), "rule__ReactDependenciesRules__DependenciesAssignment_2");
			builder.put(grammarAccess.getReactDependenciesSubRulesAccess().getDependenciesAssignment(), "rule__ReactDependenciesSubRules__DependenciesAssignment");
			builder.put(grammarAccess.getSingleDependenciesAccess().getDependenciesAssignment_0(), "rule__SingleDependencies__DependenciesAssignment_0");
			builder.put(grammarAccess.getSingleDependenciesAccess().getDependenciesAssignment_1(), "rule__SingleDependencies__DependenciesAssignment_1");
			builder.put(grammarAccess.getPackageNameAccess().getNameAssignment_1(), "rule__PackageName__NameAssignment_1");
			builder.put(grammarAccess.getPackageVersionAccess().getNameAssignment_1(), "rule__PackageVersion__NameAssignment_1");
			builder.put(grammarAccess.getReactConfigurationsAccess().getNameAssignment_1(), "rule__ReactConfigurations__NameAssignment_1");
			builder.put(grammarAccess.getReactComponentsAccess().getComponentslogicAssignment_1(), "rule__ReactComponents__ComponentslogicAssignment_1");
			builder.put(grammarAccess.getReactComponentsAccess().getComponentsuiAssignment_2(), "rule__ReactComponents__ComponentsuiAssignment_2");
			builder.put(grammarAccess.getComponentsLogicAccess().getNameAssignment_1(), "rule__ComponentsLogic__NameAssignment_1");
			builder.put(grammarAccess.getComponentsUIAccess().getNameAssignment_1(), "rule__ComponentsUI__NameAssignment_1");
			builder.put(grammarAccess.getReactActionsAccess().getNameAssignment_1(), "rule__ReactActions__NameAssignment_1");
			builder.put(grammarAccess.getReactLibrariesAccess().getNameAssignment_1(), "rule__ReactLibraries__NameAssignment_1");
			builder.put(grammarAccess.getReactInfoAccess().getNameAssignment_1(), "rule__ReactInfo__NameAssignment_1");
			builder.put(grammarAccess.getSpringAccess().getNameAssignment_1(), "rule__Spring__NameAssignment_1");
			builder.put(grammarAccess.getPostgreSQLAccess().getNameAssignment_1(), "rule__PostgreSQL__NameAssignment_1");
			builder.put(grammarAccess.getAmazonWebServicesAccess().getNameAssignment_1(), "rule__AmazonWebServices__NameAssignment_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MyDslGrammarAccess grammarAccess;

	@Override
	protected InternalMyDslParser createParser() {
		InternalMyDslParser result = new InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
