/**
 * generated by Xtext 2.18.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Layer Relations</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.LayerRelations#getLayerelations <em>Layerelations</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.LayerRelations#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.LayerRelations#getLayerorigin <em>Layerorigin</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.LayerRelations#getLayertarget <em>Layertarget</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getLayerRelations()
 * @model
 * @generated
 */
public interface LayerRelations extends EObject
{
  /**
   * Returns the value of the '<em><b>Layerelations</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Layerelations</em>' attribute list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getLayerRelations_Layerelations()
   * @model unique="false"
   * @generated
   */
  EList<String> getLayerelations();

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getLayerRelations_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.LayerRelations#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Layerorigin</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.LayerSource}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Layerorigin</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getLayerRelations_Layerorigin()
   * @model containment="true"
   * @generated
   */
  EList<LayerSource> getLayerorigin();

  /**
   * Returns the value of the '<em><b>Layertarget</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.LayerTarget}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Layertarget</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getLayerRelations_Layertarget()
   * @model containment="true"
   * @generated
   */
  EList<LayerTarget> getLayertarget();

} // LayerRelations
