/**
 * generated by Xtext 2.18.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>NTier Target</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.NTierTarget#getNtierconnection <em>Ntierconnection</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getNTierTarget()
 * @model
 * @generated
 */
public interface NTierTarget extends EObject
{
  /**
   * Returns the value of the '<em><b>Ntierconnection</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.NTiersRelations}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ntierconnection</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getNTierTarget_Ntierconnection()
   * @model containment="true"
   * @generated
   */
  EList<NTiersRelations> getNtierconnection();

} // NTierTarget
