/**
 * generated by Xtext 2.17.1
 */
package org.xtext.photos.mydsl.ide;

import org.xtext.photos.mydsl.ide.AbstractMyDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MyDslIdeModule extends AbstractMyDslIdeModule {
}
